# dash means a new step
version: 2
jobs:
  build:
      docker:
      - image: circleci/android:api-28
      working_directory: ~/SimpleWarikan
      
      environment:
      # Customize the JVM maximum heap limit
        JVM_OPTS: -Xmx3200m
        TERM: dumb
        
      steps:
        - checkout
        
        - run:
          name: Download Dependenice
          command: ./gradlew androidDependencies
        - run:
          name: build app
          command: ./gradlew assembleDebug
        - run:
          name: Android Lint
          command: ./gradlew lintDebug
        
